version: '3'

services:
  scraper:
    build: .
    container_name: scraper
    ports:
      - "5000:5000"
    networks:
      - scrapy_mysql_net
    command: ["wait-for-it", "mysql:3306", "--timeout=240","--","scrapy", "crawl", "quotes"]
  db:
    image: mysql
    container_name: db
    command: ["--init-file=/tmp/mysql-init.sql", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      MYSQL_NATIVE_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
      MYSQL_USER: 'scraper'
    volumes:
      - ./db_dir:/var/lib/mysql
      - ./mysql-init.sql:/tmp/mysql-init.sql
    networks:
      - scrapy_mysql_net
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  db_dir:

networks:
  scrapy_mysql_net:
